version: "3.7"
services:
  goilerplate-mono-local:
    build:
      context: .
      dockerfile: local.Dockerfile
    image: goilerplate-mono:local
    container_name: goilerplate-mono-local
    ports:
      - 80:80
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DBMS: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: host.docker.internal
      DB_PORT: 3066
      DB_NAME: go_auto_reload
      DB_MAX_OPEN_CONNECTION: 10
      DB_MAX_IDLE_CONNECTION: 5
      DB_MAX_CONNECTION_LIFETIME: 300s
      PORT: 
    volumes:
      - .:/app
